name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:

  build:

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10']
        tensorflow-ref: ['refs/tags/v2.9.1']
        include:
          - platform: windows-latest
            tensorflow-target: windows

    runs-on: ${{ matrix.platform }}

    steps:

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install python dependencies
        run: pip install numpy pybind11 wheel

      - name: Clone tensorflow
        uses: actions/checkout@v3
        with:
          repository: tensorflow/tensorflow
          ref: ${{ matrix.tensorflow-ref }}

      - name: Set PYTHON_BIN_PATH
        run: echo "PYTHON_BIN_PATH=$(which python)" >> $GITHUB_ENV
        shell: bash

      - name: Set TENSORFLOW_TARGET
        run: echo "TENSORFLOW_TARGET=${{ matrix.tensorflow-target }}" >> $GITHUB_ENV
        shell: bash

      - name: Environment information
        run: |
          echo "platform: ${{matrix.platform}}"
          echo "python version: ${{matrix.python-version}}"
          echo "TENSORFLOW_TARGET=$TENSORFLOW_TARGET"
          echo "PYTHON_BIN_PATH=$PYTHON_BIN_PATH"
          echo "which python3: $(which python3)"
          echo "which python: $(which python)"
        shell: bash

      - name: Build wheel
        run: |
          bash tensorflow/lite/tools/pip_package/build_pip_package_with_bazel.sh
        shell: bash
